// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function AppInfo() {
  return window['go']['main']['App']['AppInfo']();
}

export function BackupDatabase(arg1) {
  return window['go']['main']['App']['BackupDatabase'](arg1);
}

export function ChangeCredentials(arg1) {
  return window['go']['main']['App']['ChangeCredentials'](arg1);
}

export function CloseFD(arg1) {
  return window['go']['main']['App']['CloseFD'](arg1);
}

export function CreateFD(arg1) {
  return window['go']['main']['App']['CreateFD'](arg1);
}

export function DashboardStats() {
  return window['go']['main']['App']['DashboardStats']();
}

export function ExportReport(arg1) {
  return window['go']['main']['App']['ExportReport'](arg1);
}

export function GetAuthInfo() {
  return window['go']['main']['App']['GetAuthInfo']();
}

export function GetFD(arg1) {
  return window['go']['main']['App']['GetFD'](arg1);
}

export function GetRateSlabs() {
  return window['go']['main']['App']['GetRateSlabs']();
}

export function ListFDs(arg1) {
  return window['go']['main']['App']['ListFDs'](arg1);
}

export function LoadSampleData() {
  return window['go']['main']['App']['LoadSampleData']();
}

export function Login(arg1) {
  return window['go']['main']['App']['Login'](arg1);
}

export function Logout() {
  return window['go']['main']['App']['Logout']();
}

export function MaturityChart() {
  return window['go']['main']['App']['MaturityChart']();
}

export function PickBackupPath() {
  return window['go']['main']['App']['PickBackupPath']();
}

export function PickReportPath(arg1) {
  return window['go']['main']['App']['PickReportPath'](arg1);
}

export function PickRestorePath() {
  return window['go']['main']['App']['PickRestorePath']();
}

export function PreviewClosure(arg1) {
  return window['go']['main']['App']['PreviewClosure'](arg1);
}

export function PreviewFD(arg1) {
  return window['go']['main']['App']['PreviewFD'](arg1);
}

export function PreviewReport(arg1) {
  return window['go']['main']['App']['PreviewReport'](arg1);
}

export function RenewFD(arg1) {
  return window['go']['main']['App']['RenewFD'](arg1);
}

export function ResetCredentials(arg1) {
  return window['go']['main']['App']['ResetCredentials'](arg1);
}

export function RestoreDatabase(arg1) {
  return window['go']['main']['App']['RestoreDatabase'](arg1);
}

export function SaveRateSlabs(arg1) {
  return window['go']['main']['App']['SaveRateSlabs'](arg1);
}

export function SystemStatus() {
  return window['go']['main']['App']['SystemStatus']();
}

export function UpcomingMaturities(arg1) {
  return window['go']['main']['App']['UpcomingMaturities'](arg1);
}
