// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {brand} from '../models';
import {api} from '../models';
import {domain} from '../models';

export function AppInfo():Promise<brand.Info>;

export function BackupDatabase(arg1:string):Promise<string>;

export function ChangeCredentials(arg1:api.ChangeCredentialsRequest):Promise<api.AuthInfo>;

export function CloseFD(arg1:api.CloseRequest):Promise<api.FD>;

export function CreateFD(arg1:api.PreviewRequest):Promise<api.FD>;

export function DashboardStats():Promise<api.DashboardStats>;

export function ExportReport(arg1:api.ReportRequest):Promise<api.ReportResult>;

export function GetAuthInfo():Promise<api.AuthInfo>;

export function GetFD(arg1:string):Promise<api.FDDetail>;

export function GetRateSlabs():Promise<Array<domain.RateSlab>>;

export function ListFDs(arg1:api.ListRequest):Promise<api.ListResponse>;

export function LoadSampleData():Promise<number>;

export function Login(arg1:api.LoginRequest):Promise<void>;

export function Logout():Promise<void>;

export function MaturityChart():Promise<Array<api.MaturityBucket>>;

export function PickBackupPath():Promise<string>;

export function PickReportPath(arg1:string):Promise<string>;

export function PickRestorePath():Promise<string>;

export function PreviewClosure(arg1:api.CloseRequest):Promise<api.ClosurePreview>;

export function PreviewFD(arg1:api.PreviewRequest):Promise<api.Calculation>;

export function PreviewReport(arg1:api.ReportRequest):Promise<api.ReportPreview>;

export function RenewFD(arg1:api.RenewRequest):Promise<api.RenewResult>;

export function ResetCredentials(arg1:api.ResetCredentialsRequest):Promise<api.AuthInfo>;

export function RestoreDatabase(arg1:string):Promise<void>;

export function SaveRateSlabs(arg1:api.SaveSlabsRequest):Promise<void>;

export function SystemStatus():Promise<api.SystemStatus>;

export function UpcomingMaturities(arg1:api.UpcomingRequest):Promise<Array<api.UpcomingFD>>;
